import { pathExists, readText } from '../../shared/fs.js';
import path from 'node:path';
import type { RepairJob } from '../jobs/job.js';
import type { GuardReport } from './guards.js';

export async function buildPrBody(workspace: string, job: RepairJob, guard: GuardReport): Promise<string> {
  const resultFile = path.join(workspace, '.fixbot', 'result.md');
  const result = await pathExists(resultFile) ? await readText(resultFile) : '_Agent did not write `.fixbot/result.md`; publisher generated this fallback body._';
  return `${result}

---

Generated by FixBot for ${job.issue.url}.

Human review required: ${job.config.policy.requireHumanReview ? 'yes' : 'no'}

Changed files: ${guard.changedFiles.length}
Diff lines: ${guard.diffLines}

Fixes #${job.issueNumber}
`;
}
